# Generated by Django 2.0.7 on 2018-08-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outeruser',
            options={'permissions': [('can_set_username', '能够更改其他用户的姓名和权限'), ('can_set_user_qrcode_permission', '能够更改其他用户是否可以添加二维码')], 'verbose_name': '用户管理'},
        ),
        migrations.AlterField(
            model_name='outeruser',
            name='wechat_id',
            field=models.CharField(max_length=100, verbose_name='微信open_id'),
        ),
    ]
