# Generated by Django 2.0.7 on 2018-08-02 04:39
from django.contrib.auth.models import User
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations
from django.conf import settings


def create_default_group(apps, schema_editor):
    emit_post_migrate_signal(2, False, 'default')
    from django.contrib.auth.models import User
    GroupModel = apps.get_model('auth', 'group')
    User.objects.create_superuser(username=settings.ADMIN_USERNAME,
                                       password=settings.ADMIN_PASSWORD,
                                       email='1@qq.com'
                                       )

    group = GroupModel(name='admin group')
    group.save()
    GroupModel(name='normal group').save()

    PermissionModel = apps.get_model('auth', 'permission')
    permission1 = PermissionModel.objects.get(codename='can_set_username')
    permission2 = PermissionModel.objects.get(codename='can_set_user_qrcode_permission')
    group.permissions.add(permission1)
    group.permissions.add(permission2)


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_auto_20180802_1151'),
        ('auth', '__latest__'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(create_default_group)
    ]
